export const GENERATION_RANGES = {
    'all': { start: 1, end: 1025 },
    'generation-i': { start: 1, end: 151 },
    'generation-ii': { start: 152, end: 251 },
    'generation-iii': { start: 252, end: 386 },
    'generation-iv': { start: 387, end: 493 },
    'generation-v': { start: 494, end: 649 },
    'generation-vi': { start: 650, end: 721 },
    'generation-vii': { start: 722, end: 809 },
    'generation-viii': { start: 810, end: 905 },
    'generation-ix': { start: 906, end: 1025 },
};

export const LEGENDARY_IDS = new Set([
    144, 145, 146, 150, 151,
    243, 244, 245, 249, 250, 251,
    377, 378, 379, 380, 381, 382, 383, 384, 385, 386,
    480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
    494, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
    716, 717, 718, 719, 720, 721,
    785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809,
    888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 905,
    1001, 1002, 1003, 1004, 1007, 1008, 1009, 1010, 1014, 1015, 1016, 1017, 1024, 1025,
]);

export const NATURES_LIST = [
    { name: 'Hardy', plus: null, minus: null },
    { name: 'Lonely', plus: 'Attack', minus: 'Defense' },
    { name: 'Brave', plus: 'Attack', minus: 'Speed' },
    { name: 'Adamant', plus: 'Attack', minus: 'Sp. Atk' },
    { name: 'Naughty', plus: 'Attack', minus: 'Sp. Def' },
    { name: 'Bold', plus: 'Defense', minus: 'Attack' },
    { name: 'Docile', plus: null, minus: null },
    { name: 'Relaxed', plus: 'Defense', minus: 'Speed' },
    { name: 'Impish', plus: 'Defense', minus: 'Sp. Atk' },
    { name: 'Lax', plus: 'Defense', minus: 'Sp. Def' },
    { name: 'Timid', plus: 'Speed', minus: 'Attack' },
    { name: 'Hasty', plus: 'Speed', minus: 'Defense' },
    { name: 'Serious', plus: null, minus: null },
    { name: 'Jolly', plus: 'Speed', minus: 'Sp. Atk' },
    { name: 'Naive', plus: 'Speed', minus: 'Sp. Def' },
    { name: 'Modest', plus: 'Sp. Atk', minus: 'Attack' },
    { name: 'Mild', plus: 'Sp. Atk', minus: 'Defense' },
    { name: 'Quiet', plus: 'Sp. Atk', minus: 'Speed' },
    { name: 'Bashful', plus: null, minus: null },
    { name: 'Rash', plus: 'Sp. Atk', minus: 'Sp. Def' },
    { name: 'Calm', plus: 'Sp. Def', minus: 'Attack' },
    { name: 'Gentle', plus: 'Sp. Def', minus: 'Defense' },
    { name: 'Sassy', plus: 'Sp. Def', minus: 'Speed' },
    { name: 'Careful', plus: 'Sp. Def', minus: 'Sp. Atk' },
    { name: 'Quirky', plus: null, minus: null },
];

export const POKEMON_TIPS = [
    "Did you know Pikachu was inspired by a squirrel, not a mouse? The name comes from 'pika' (sparkle) + 'chu' (squeak sound in Japan)!",
    "Ditto can transform into any Pokémon, but its eyes remain the same - a detail that helps identify it!",
    "Magikarp can leap over mountains with its Splash, but the move still deals no damage... ironic, right?",
    "Slowpoke takes 5 seconds to feel pain. If its tail is bitten, it won't notice until much later!",
    "Cubone wears the skull of its deceased mother as a helmet. No one has ever seen its true face.",
    "Gengar might be Clefable's shadow - they have almost identical silhouettes!",
    "Vaporeon is composed of molecules so similar to water that it can become invisible when submerged.",
    "Alakazam has an IQ of 5000, making it smarter than any supercomputer!",
    "Shedinja has only 1 HP, but its Wonder Guard ability makes it immune to non-super effective moves.",
    "Wobbuffet hides its true body - the black tail with eyes is the real Pokémon!",
    "Arcanine was originally planned to be a legendary Pokémon, which is why it's called the 'Legendary Pokémon' in the Pokédex.",
    "Rhydon was the first Pokémon ever created, not Bulbasaur!",
    "Espeon and Umbreon represent the sun and the moon, evolving according to the time of day.",
    "Mewtwo was cloned from Mew, but ended up becoming much more powerful than the original.",
    "Tyranitar can bring down whole mountains and change the landscape when it's furious!",
    "Eevee has the most possible evolutions of any Pokémon, currently totaling eight different forms!",
    "Porygon is the first artificial Pokémon, created entirely out of programming code.",
    "Dragonite can circle the globe in just 16 hours, flying at roughly 1,500 mph.",
    "Lapras is known for its high intelligence and can understand human speech.",
    "Snorlax's stomach is so strong it can digest rotten food without getting sick.",
    "Farfetch'd carries a leek stalk as a weapon, but it will also eat it if it gets hungry enough!",
    "Psyduck suffers from constant headaches. When the pain becomes too intense, it unleashes powerful psychic energy.",
    "Meowth is the only Pokémon in the anime that taught itself to speak human language to impress a female Meowth.",
    "Machamp can throw 500 punches in a single second with its four arms!",
    "Gyarados is known as the Atrocious Pokémon because of its violent temper, often destroying entire cities in a rage.",
    "Jigglypuff's song is so soothing that no one can stay awake to hear the whole thing.",
    "Haunter can lick you with its gaseous tongue to steal your life force. Spooky!",
    "Kangaskhan is never seen without its baby in its pouch until the baby is fully grown.",
    "Mr. Mime creates invisible walls by vibrating its fingertips at high speeds.",
    "Scyther moves so fast that it looks like there are several of them at once, creating a ninja-like illusion.",
    "Electabuzz loves to feed on electricity and can often be found near power plants causing blackouts.",
    "Magmar's body temperature is nearly 2,200 degrees Fahrenheit, making it a walking fireball.",
    "Tauros whips itself with its three tails to get pumped up for battle.",
    "Ditto cannot copy a Pokémon's HP stat, which is why it often transforms into high-HP Pokémon in competitive play.",
    "Eevee's genetic code is unstable, which is why it can evolve into so many different types.",
    "Kabutops was an ancient predator that swam in the oceans 300 million years ago.",
    "Aerodactyl was resurrected from DNA found in amber, much like the dinosaurs in Jurassic Park!",
    "Articuno's wings are said to be made of ice, and it can create blizzards just by flapping them.",
    "Zapdos is capable of controlling thunderstorms and gains power when struck by lightning.",
    "Moltres heals its wounds by dipping itself into the magma of an active volcano.",
    "Dratini was once considered a myth until a fishing colony found one underwater.",
    "Mew contains the DNA of every single Pokémon, making it the ancestor of all Pokémon.",
    "Chikorita uses the leaf on its head to check the temperature and humidity of the air.",
    "Cyndaquil flares the flames on its back when it is angry or startled.",
    "Totodile has a habit of biting anything it sees, including its trainer!",
    "Sentret stands on its tail to scout for danger from a distance.",
    "Hoothoot has an internal organ that senses the earth's rotation, keeping perfect time.",
    "Ledyba communicates with others using scents that change depending on its feelings.",
    "Spinarak spins a web that is strong enough to trap small prey, and it waits patiently for days.",
    "Pichu is not yet skilled at storing electricity and may accidentally discharge it when startled.",
    "Cleffa is often seen dancing in a ring on nights with a full moon.",
    "Igglybuff has a very soft and elastic body, allowing it to bounce like a ball.",
    "Togepi stores happiness inside its shell and shares it with those who treat it well.",
    "Natu cannot fly yet, so it hops around to get from place to place.",
    "Mareep's wool grows continuously and stores static electricity. Touching it can give you a shock!",
    "Bellossom is the only Pokémon that evolves from a dual-type (Gloom) into a single-type.",
    "Marill's tail functions like a float, keeping it above water even in strong currents.",
    "Sudowoodo pretends to be a tree to avoid being attacked, but it hates water!",
    "Shedinja is the only Pokémon that always has exactly 1 HP, regardless of its level.",
    "Smeargle can permanently learn almost any move in the game using Sketch.",
    "Azurill can change gender when evolving into Marill due to different gender ratios.",
    "Nincada is the only Pokémon that can evolve into two Pokémon at the same time: Ninjask and Shedinja.",
    "Wailord is one of the largest Pokémon ever, yet it weighs less than many much smaller Pokémon.",
    "Feebas evolves through beauty in some games, making it one of the most unusual evolution methods.",
    "Spiritomb originally had no weaknesses before the Fairy type was introduced in Generation VI.",
    "Regigigas suffers from Slow Start, cutting its Attack and Speed in half for the first five turns.",
    "Castform changes form depending on the weather, making it one of the earliest form-changing Pokémon.",
    "Burmy changes its cloak based on the environment where battles occur.",
    "Rotom can possess household appliances, changing both its appearance and type.",
    "Wishiwashi transforms from a tiny fish into a giant school when it reaches a certain level.",
    "Aegislash is one of the few Pokémon capable of changing its stats during battle through form changes.",
    "Minior's colorful core is hidden beneath a rocky shell that breaks during combat.",
    "Darmanitan can enter Zen Mode, completely changing its appearance and battle role.",
    "Zoroark can create powerful illusions, disguising itself as another Pokémon.",
    "Mimikyu wears a Pikachu costume because it believes people will love it more that way.",
    "Falinks is actually made up of several individual creatures marching together as one Pokémon.",
    "Tandemaus evolves into Maushold, but the family gains new members seemingly out of nowhere.",
    "Palafin appears weak at first, but transforms into a superhero-like form after switching out.",
    "Inkay evolves only if you level it up while holding your console upside down.",
    "Yamask evolves by taking a specific amount of damage and passing under a special structure.",
    "Galarian Farfetch'd evolves only after landing multiple critical hits in a single battle.",
    "Runerigus has one of the most complicated evolution methods in Pokémon history.",
    "Mantyke requires a Remoraid in your party to evolve into Mantine.",
    "Pangoro evolves only if a Dark-type Pokémon is in your party.",
    "Malamar is one of the few Pokémon whose evolution depends on a real-world action from the player.",
    "Eevee has more evolution methods than any other Pokémon family.",
    "Arceus can change its type using Plates, effectively becoming any type in the game.",
    "Silvally was created to mimic Arceus and can also change its type.",
    "The move Struggle can never run out of PP because it appears when all other moves are depleted.",
    "The move Splash is famous for doing nothing, but in some spin-off games it actually has effects.",
    "False Swipe can never knock out a Pokémon, making it perfect for catching wild Pokémon.",
    "Thunder always hits during rain unless another effect overrides accuracy.",
    "Hurricane and Thunder become much more reliable in rainy weather.",
    "Blizzard gains perfect accuracy during hail or snow conditions.",
    "A Pokémon's shininess is determined the moment it is generated, not when you encounter it.",
    "Shiny Pokémon were introduced in Generation II alongside the breeding system.",
    "The original shiny odds were 1 in 8192, much lower than modern games.",
    "Pokérus is rarer than a shiny Pokémon and provides faster EV training.",
    "Unown has 28 different forms representing letters and punctuation marks.",
    "Spinda has billions of possible spot patterns, making nearly every Spinda unique.",
    "Vivillon's wing patterns change depending on the real-world region where it was obtained.",
    "Furfrou can receive multiple trims, but they revert after being stored in Pokémon Bank or HOME.",
    "Melmetal is the first Pokémon species created specifically for Pokémon GO.",
    "Eternatus has the highest base stat total of any non-Mega, non-form-changing Pokémon.",
    "Slaking has legendary-level stats, but is balanced by its Truant ability.",
    "Ditto and Mew are the only Pokémon that naturally learn Transform.",
    "The Master Ball has never failed in the main series games under normal circumstances.",
    "Some Pokémon can only evolve in specific locations, times, or weather conditions.",
    "Several Pokémon species are based on extinct animals, myths, or real-world folklore."
];
